# Generated by Django 2.2.1 on 2019-05-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecievedFax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('sender', models.CharField(max_length=15)),
                ('document', models.FileField(upload_to='inbox/')),
            ],
        ),
        migrations.CreateModel(
            name='SentFax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('recipient', models.CharField(max_length=15)),
                ('document', models.FileField(upload_to='sent/')),
            ],
        ),
    ]
