# Generated by Django 2.2.1 on 2019-05-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recievedfax',
            name='sender',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='sentfax',
            name='recipient',
            field=models.CharField(max_length=12),
        ),
    ]
